version: '3.8'

services:
  backend:
    build:
      context: ./backend
    command: gunicorn app.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - ./backend:/app
    env_file:
      - ./backend/.env
    expose:
      - 8000

  frontend:
    build:
      context: ./frontend
    depends_on:
      - backend

  nginx:
    image: nginx:alpine
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    ports:
      - "80:80"
    depends_on:
      - backend
      - frontend
