version: '3.9'
services:
  db:
    image: postgres:15
    env_file:
      - .env
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  backend:
    build: ./backend
    env_file:
      - .env
    depends_on:
      - db
    volumes:
      - ./backend/media:/app/media
    ports:
      - "8000:8000"

  frontend:
    build:
      context: .
      dockerfile: cookbook-app/Dockerfile
    depends_on:
      - backend
    ports:
      - "80:80"

volumes:
  postgres_data:
