#!/usr/bin/env bash

# Shared Docker Compose configuration for production lifecycle scripts.

COMPOSE_ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/../.." && pwd)"
COMPOSE_CONFIG_PATH="${EMMA_COMPOSE_CONFIG:-${COMPOSE_ROOT_DIR}/.emma-compose.env}"

if [[ -f "${COMPOSE_CONFIG_PATH}" ]]; then
  # This file is generated by setup_docker_production.sh and contains only
  # deployment paths and Compose settings.
  # shellcheck disable=SC1090
  source "${COMPOSE_CONFIG_PATH}"
fi

ENV_FILE_PATH="${ENV_FILE:-${EMMA_ENV_FILE:-${COMPOSE_ROOT_DIR}/.env.production}}"
EMMA_COMPOSE_FILES="${EMMA_COMPOSE_FILES:-docker-compose.yml}"
COMPOSE_PROJECT_NAME="${COMPOSE_PROJECT_NAME:-emma-cookbook}"

compose_run() {
  local args=()
  local interpolation_args=()
  local relative_file
  local compose_file
  local files="${EMMA_COMPOSE_FILES}"

  while [[ -n "${files}" ]]; do
    relative_file="${files%%:*}"
    if [[ "${files}" == *:* ]]; then
      files="${files#*:}"
    else
      files=""
    fi
    if [[ "${relative_file}" = /* ]]; then
      compose_file="${relative_file}"
    else
      compose_file="${COMPOSE_ROOT_DIR}/${relative_file}"
    fi
    args+=(-f "${compose_file}")
  done

  if [[ -f "${COMPOSE_ROOT_DIR}/.env" ]]; then
    interpolation_args=(--env-file "${COMPOSE_ROOT_DIR}/.env")
  fi

  ENV_FILE="${ENV_FILE_PATH}" \
  COMPOSE_PROJECT_NAME="${COMPOSE_PROJECT_NAME}" \
  docker compose "${interpolation_args[@]}" "${args[@]}" "$@"
}
